version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://srv-captain--orbi-db:5432/keycloak
      - SPRING_R2DBC_URL=jdbc:postgresql://srv-captain--orbi-db:5432/keycloak
      - SPRING_R2DBC_USERNAME=keycloak
      - SPRING_R2DBC_PASSWORD=1cbe2e406a7de389db53f
